### ISSUE TITLE
libsec no longer works on MacOS?

### ISSUE THREAD

**Issue by mflaxman** [buidl-bitcoin/buidl-python#98]
```
$ brew tap buidl-bitcoin/libsecp256k1

$ brew install pkg-config libffi

$ brew install libsecp256k1
==> Cloning https://github.com/bitcoin/secp256k1.git
Updating /Users/mflaxman/Library/Caches/Homebrew/libsecp256k1--git
origin/HEAD set to master
refs/remotes/origin/master
==> Checking out revision 98dac87839838b86094f1bccc71cc20e67b146cc
HEAD is now at 98dac87 Merge #858: Fix insecure links
HEAD is now at 98dac87 Merge #858: Fix insecure links
==> Installing libsecp256k1 from buidl-bitcoin/libsecp256k1
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/libsecp256k1/0.1 --enable-module-extrakeys --enable-module-schnorrsig --enable-experimental
==> make install
🍺  /usr/local/Cellar/libsecp256k1/0.1: 12 files, 622.5KB, built in 31 seconds

$ python libsec_build.py 
generating ./_libsec.c
(already up-to-date)
the current directory is '/Users/mflaxman/workspace/buidl-python/buidl'
running build_ext
building '_libsec' extension
cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _libsec.c -o ./_libsec.o
_libsec.c:1452:54: error: too few arguments to function call, expected 6, have 5
  return secp256k1_schnorrsig_sign(x0, x1, x2, x3, x4);
         ~~~~~~~~~~~~~~~~~~~~~~~~~                   ^
/usr/local/include/secp256k1_schnorrsig.h:82:19: note: 'secp256k1_schnorrsig_sign' declared here
SECP256K1_API int secp256k1_schnorrsig_sign(
                  ^
_libsec.c:1523:58: error: too few arguments to function call, expected 6, have 5
  { result = secp256k1_schnorrsig_sign(x0, x1, x2, x3, x4); }
             ~~~~~~~~~~~~~~~~~~~~~~~~~                   ^
/usr/local/include/secp256k1_schnorrsig.h:82:19: note: 'secp256k1_schnorrsig_sign' declared here
SECP256K1_API int secp256k1_schnorrsig_sign(
                  ^
_libsec.c:1538:54: error: too many arguments to function call, expected 4, have 5
  return secp256k1_schnorrsig_verify(x0, x1, x2, x3, x4);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~                 ^~
/usr/local/include/secp256k1_schnorrsig.h:100:48: note: 'secp256k1_schnorrsig_verify' declared here
SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_schnorrsig_verify(
                                               ^
_libsec.c:1604:58: error: too many arguments to function call, expected 4, have 5
  { result = secp256k1_schnorrsig_verify(x0, x1, x2, x3, x4); }
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~                 ^~
/usr/local/include/secp256k1_schnorrsig.h:100:48: note: 'secp256k1_schnorrsig_verify' declared here
SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_schnorrsig_verify(
                                               ^
_libsec.c:1619:10: error: implicit declaration of function 'secp256k1_tagged_sha256' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  return secp256k1_tagged_sha256(x0, x1, x2, x3, x4, x5);
         ^
_libsec.c:1691:14: error: implicit declaration of function 'secp256k1_tagged_sha256' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  { result = secp256k1_tagged_sha256(x0, x1, x2, x3, x4, x5); }
             ^
6 errors generated.
Traceback (most recent call last):
  File "libsec_build.py", line 15, in <module>
    ffi.compile(verbose=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/cffi/api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/cffi/recompiler.py", line 1555, in recompile
    compiler_verbose, debug)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command 'cc' failed with exit status 1
```

I created this tap to make installing easy:
https://github.com/buidl-bitcoin/homebrew-libsecp256k1/

Are there any other flags I need to pass?

**Comment by jimmysong** [comment]
Try github.com/bitcoin-core/secp256k1 instead of the bitcoin one.
